# Generated by Django 4.0.6 on 2022-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Year', models.CharField(max_length=500)),
                ('Duration', models.CharField(max_length=500)),
                ('Rating', models.CharField(max_length=500)),
                ('MetaScore', models.CharField(max_length=500)),
                ('Vote', models.CharField(max_length=500)),
                ('Gross', models.CharField(max_length=500)),
            ],
        ),
    ]
